name: codequality

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  linting:
    name: Linting Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Run ESLint
        run: npx eslint .



  
 



 
