name: codequality tes

on:
 push:
   branches:
     -master 
 workflow_dispatch:

jobs:
 linting:
   name: linting_project
   runs-on: ubuntu:latest
   steps:
    - uses: actions/checkout@v2
    - name: "checking out"

    - run: npm install eslint
    - run: npx eslint 


  
 



 
